apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
        name: get_pods
        namespace: default
rules:
        - apiGroups: [""]
          resources: ["pods", "services", "serviceaccounts"]
          verbs: ["get", "watch", "list"]
