apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: get_pods
        namespace: default
subjects:
        - name: demo-sa
          kind: ServiceAccount
          apiGroup: ""
roleRef:
        name: get_pods
        kind: Role
        apiGroup: rbac.authorization.k8s.io
