#this secret will use to generate log lived token for our SA and attach it to our SA as we entioned in annotaions.

apiVersion: v1
kind: Secret
metadata:
        name: demo-sa-token
        annotations: 
                kubernetes.io/service-account.name: demo-sa
type: kubernetes.io/service-account-token
